name: Deploy to GitHub Pages

on:
  push:
    branches: [main]        # every commit triggers a redeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Install deps & build the static site
      - uses: actions/setup-node@v4
        with: {node-version: 20}
      - run: npm ci           # or pnpm i / yarn install
      - run: npm run build    # creates ./dist  (adjust if Bolt made a /build folder)

      # 2. Push the dist folder to the gh-pages branch
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # ↖️  same path you built above